# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lachlan McCarty
email: lachlan@lachm.com
description: > # this means to ignore newlines until "baseurl:"
  lachm.com is the personal website of Lachlan McCarty, a Princeton University
  undergraduate with strong interests in tech and computer science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lachm.com" # the base hostname & protocol for your site
twitter_username: lachm_
github_username:  lachm

timezone: America/New_York

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "_posts"
    values:
      permalink: /posts/:title/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
